parameters:
  test.one.command.class: App\TestOneBundle\Command\TestOneCommand

services:
  test.one.command:
    class: "%test.one.command.class%"
    public: true
    tags:
      - { name: command }
    arguments:
      - '@App\TestOneBundle\Services\Connector'

  App\TestOneBundle\Services\:
    resource: '../../Services/*'
  App\TestOneBundle\Services\Connector:
    arguments:
      - '@App\TestOneBundle\Services\ProductManager'
      - '@App\TestOneBundle\Services\UserManager'
      - '@App\TestOneBundle\Services\CartManager'
      - '@App\TestOneBundle\Services\OrderManager'
      - '@App\TestOneBundle\Services\InvoiceManager'